name: docker_build
description: docker_build
inputs:
  path:
    description: "Dockerfile name"
    required: false
    default: "Dockerfile"
  tag:
    description: "Docker Tag"
    required: false
    default: "$(date +%s)"
runs:
  using: composite
  steps:
    - run: |
        docker build . --file ${{inputs.path}} --tag academy:${{inputs.tag}}
      shell: bash