name: docker_build
description: docker_build
inputs:
  path:
    description: "Dockerfile name"
    required: false
    default: "Dockerfile"
  tag:
    description: "Docker Tag"
    required: false
    default: "$(date +%s)"
  image_name:
    description: "Docker Image Name"
    required: true
runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag }}" ]; then
            export TAG=$(date +%s)
        else
            export TAG="${{ inputs.tag }}"
        fi
        docker build . --file ${{inputs.path}} --tag ${{inputs.image_name}}:$TAG
      shell: bash