name: docker_push
description: Pushing image to docker hub
inputs:
  tag:
    description: "Docker Tag"
    required: true
  image_name:
    description: "Docker Image Name"
    required: true
  username:
    description: "Docker Hub Username"
    required: true
runs:
  using: composite
  steps:
    - run: |
        docker tag ${{inputs.tag}} ${{inputs.image_name}} ${{inputs.username}}/${{inputs.image_name}}:${{inputs.tag}}
        docker push ${{inputs.username}}/${{inputs.image_name}}:${{inputs.tag}}
      shell: bash