# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

run-name: Docker build and push to ${{inputs.environment}}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environments available
        required: true
        default: Test
        type: choice
        options:
          - Test
          - Int
          - E2E
          - Prod

env:
  docker_image_name: academy
  docker_tag_name: ${{env.docker_tag_name}}-${{inputs.environment}}
  uploaded_docker_image: academy_docker_image
  POSTGRES_USERNAME: academy
  POSTGRES_PASSWORD: academy
  POSTGRES_DATABASE: postgres

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{env.POSTGRES_USERNAME}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{env.POSTGRES_DATABASE}}
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/maven_build
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - uses: ./.github/actions/docker_build
      with:
        image_name: $docker_image_name
        tag: $docker_tag_name
    - name: save Docker image
      run: docker save -o $docker_image_name.tar $docker_image_name:$docker_tag_name
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.uploaded_docker_image }}
        path: ${{ env.docker_image_name }}.tar

#    - name: Setup new docker image and list
#      run: docker build . --tag academy:$(date +%s)

  list_docker_images:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: ${{ env.uploaded_docker_image }}
    - run: docker load -i ${{ env.docker_image_name }}.tar
    - name: List docker images
      run: docker image ls

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: ./.github/actions/docker_push
      with:
        image_name: ${{ env.docker_image_name }}
        tag: ${{ env.docker_tag_name }}
        username: ${{ vars.DOCKERHUB_USERNAME }}

#    - name: Run Quarkus Tests
#      run: